[features]
seeds = false
skip-lint = false
[programs.localnet]
history_validator = "TeYFdwrzRmWfTTWBnH6cMGKBHvvuX54obGnP3A8JnpJ"

[programs.devnet]
history_validator = "TeYFdwrzRmWfTTWBnH6cMGKBHvvuX54obGnP3A8JnpJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/iminakov/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
